# Defines what image we want to start from
# TIP: You can start from your own images
FROM docker/whalesay

# A helpful label to know who created this
LABEL MAINTAINER="Derek Smith"

# Overriding the command to provide our own arguments
CMD ["coway", "Hello from Derek!"]